In [3]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

# Standard Python loop approac
result_loop = []
for value in x:
    result_loop.append(value ** 2)

# Vectorized approach:
result_vectorized = x ** 2

# Task 1:
y = 2 * x + 5
print("x:", x)
print("y (2x + 5):", y)

x: [1 2 3 4 5]
y (2x + 5): [ 7  9 11 13 15]


In [2]:
""" Questions & Answers for Part A
- What is vectorization?
Vectorization is the process of executing operations directly on entire arrays or data vectors at once, delegating loops to low-level compiled C code underlying NumPy.
- Why is vectorization useful?
It produces cleaner, shorter code and dramatically speeds up computation times compared to standard Python loops.
- What is the difference between a Python loop and a NumPy vectorized operation?
A Python loop iterates over each element one at a time at the interpreted Python level (incurring type-checking and interpreter overhead for every element), whereas a NumPy vectorized operation executes C-level compiled, contiguous memory operations over array elements simultaneously. """

' Questions & Answers for Part A\n- What is vectorization?\nVectorization is the process of executing operations directly on entire arrays or data vectors at once, delegating loops to low-level compiled C code underlying NumPy.\n- Why is vectorization useful?\nIt produces cleaner, shorter code and dramatically speeds up computation times compared to standard Python loops.\n- What is the difference between a Python loop and a NumPy vectorized operation?\nA Python loop iterates over each element one at a time at the interpreted Python level (incurring type-checking and interpreter overhead for every element), whereas a NumPy vectorized operation executes C-level compiled, contiguous memory operations over array elements simultaneously. '

In [4]:
# PART B
marks = np.array([40, 55, 62, 70, 81, 90])

# Add 5 marks to every student score
adjusted = marks + 5
print("Adjusted marks:", adjusted)

# Calculate percentage proportion
percentage = marks / 100
print("Percentages:", percentage)

# Task 2: Calculate standardized value (z-scores)
# Formula: z_i = (x_i - mean(x)) / s
z = (marks - np.mean(marks)) / np.std(marks)
print("Standardized z-scores:", z)

# Verify mean of z is approximately zero
print("Mean of z-scores:", np.mean(z))

Adjusted marks: [45 60 67 75 86 95]
Percentages: [0.4  0.55 0.62 0.7  0.81 0.9 ]
Standardized z-scores: [-1.59799895 -0.68774638 -0.26296185  0.22250618  0.89002473  1.43617627]
Mean of z-scores: 2.590520390792032e-16


In [6]:
# PART C
data = np.array([
    [60, 70, 80],
    [50, 65, 75],
    [90, 85, 95]
])

adjustment = np.array([5, 0, 2])

# Element-wise addition across rows using broadcasting
result = data + adjustment
print("Result matrix after broadcasting:\n", result)

# PART C QUESTION AND ANSWER
# This works because of broadcasting rules in NumPy

Result matrix after broadcasting:
 [[65 70 82]
 [55 65 77]
 [95 85 97]]


In [7]:
# PART D
data = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

# Calculate column means
means = data.mean(axis=0)
print("Column means:", means)  # Output: [20. 30. 40.]

# Center each column by subtracting column means
centered = data - means
print("Centered matrix:\n", centered)

# Task 3: Verify that column means of centered data are approximately 0
print("Means of centered columns:", centered.mean(axis=0))

Column means: [20. 30. 40.]
Centered matrix:
 [[-10. -10. -10.]
 [  0.   0.   0.]
 [ 10.  10.  10.]]
Means of centered columns: [0. 0. 0.]


In [8]:
""" PART D question and answer
The 1D vector means has shape (3,). When subtracting it from the 2D matrix data of shape (3, 3), NumPy applies broadcasting rules. It aligns the trailing dimension (3 columns) and automatically expands means across all rows, subtracting means[0] from column 1, means[1] from column 2, and means[2] from column 3 across every row."""

' PART D question and answer\nThe 1D vector means has shape (3,). When subtracting it from the 2D matrix data of shape (3, 3), NumPy applies broadcasting rules. It aligns the trailing dimension (3 columns) and automatically expands means across all rows, subtracting means[0] from column 1, means[1] from column 2, and means[2] from column 3 across every row.'

In [11]:
# PART E
x = np.arange(1_000_000)

# Approach 1: Python Loop
result_loop = []
for value in x:
    result_loop.append(value**2 + 2*value + 1)

# Approach 2: NumPy Vectorized
result_vectorized = x**2 + 2*x + 1

# Check if both agree
print("Do both results agree?", np.allclose(result_loop, result_vectorized))

Do both results agree? True


In [12]:
""" Part E Questions & Answers
1. Yes, np.allclose(result_loop, result_vectorized) evaluates to True.   
2. The vectorized approach (x**2 + 2*x + 1) is far easier to read because it matches standard mathematical notation without boilerplate loop syntax.
3. The NumPy vectorized approach.   
4. NumPy executes array operations using pre-compiled, C-level contiguous memory blocks and SIMD (Single Instruction, Multiple Data) processor instructions, whereas Python loops repeatedly execute dynamic type checks, object overhead, and list allocations for every single element """

' Part E Questions & Answers\n1. Yes, np.allclose(result_loop, result_vectorized) evaluates to True.   \n2. The vectorized approach (x**2 + 2*x + 1) is far easier to read because it matches standard mathematical notation without boilerplate loop syntax.\n3. The NumPy vectorized approach.   \n4. NumPy executes array operations using pre-compiled, C-level contiguous memory blocks and SIMD (Single Instruction, Multiple Data) processor instructions, whereas Python loops repeatedly execute dynamic type checks, object overhead, and list allocations for every single element '

In [13]:
# PART F
np.random.seed(123)
x = np.random.normal(100, 15, 100_000)

# Calculate standardized values
z = (x - x.mean()) / x.std()

# Verify mean and standard deviation
print("Mean of z:", z.mean())
print("Std Dev of z:", z.std())

Mean of z: -9.839595804805867e-16
Std Dev of z: 0.9999999999999999


In [14]:
""" Why vectorization is particularly useful when working with large statistical datasets:
Large datasets (like 100,000+ observations) require high-performance computation. Vectorization avoids Python's iteration overhead, running array transformations in milliseconds rather than seconds or minutes, making large-scale simulations, bootstrap resamplings, and matrix operations computationally efficient """

" Why vectorization is particularly useful when working with large statistical datasets:\nLarge datasets (like 100,000+ observations) require high-performance computation. Vectorization avoids Python's iteration overhead, running array transformations in milliseconds rather than seconds or minutes, making large-scale simulations, bootstrap resamplings, and matrix operations computationally efficient "

In [15]:
# LAB 3 CHALLENGE
# 1. Standardize a 1D NumPy array
def standardize(x):
    return (x - np.mean(x)) / np.std(x)

# Test with three different arrays
test1 = np.array([10, 20, 30, 40, 50])
test2 = np.array([1.5, 2.3, 4.8, 9.1, 12.4])
test3 = np.array([-100, 0, 100, 200])

print("Test Array 1 Standardized:", standardize(test1))
print("Test Array 2 Standardized:", standardize(test2))
print("Test Array 3 Standardized:", standardize(test3))

# 2. Standardize a 2D dataset column by column
def standardize_2d(x):
    return (x - np.mean(x, axis=0)) / np.std(x, axis=0)

# Test with a 2D matrix
matrix_data = np.array([
    [10, 500, 1.0],
    [20, 600, 2.0],
    [30, 700, 3.0],
    [40, 800, 4.0]
])

standardized_matrix = standardize_2d(matrix_data)
print("\nStandardized 2D Matrix:\n", standardized_matrix)
print("Column Means (should be ~0):", standardized_matrix.mean(axis=0))
print("Column Standard Deviations (should be 1):", standardized_matrix.std(axis=0))

Test Array 1 Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Test Array 2 Standardized: [-1.09019842 -0.89724295 -0.2942571   0.74287857  1.5388199 ]
Test Array 3 Standardized: [-1.34164079 -0.4472136   0.4472136   1.34164079]

Standardized 2D Matrix:
 [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
Column Means (should be ~0): [0. 0. 0.]
Column Standard Deviations (should be 1): [1. 1. 1.]
